language: go
go:
  - master
env:
  - GO111MODULE=on
script:
  - go vet ./...
  - go test -v -covermode=atomic -coverpkg ./... -coverprofile coverage.txt ./...
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
